export const validCategories = [
  "all",
  "frontend",
  "backend",
  "fullstack",
  "mobile",
  "devops",
  "cloud",
  "containerization",
  "cicd",
  "databases",
  "machine-learning",
  "data-science",
  "web-basics",
  "frameworks",
  "languages",
  "version-control",
  "testing",
  "build-tools",
  "security",
  "apis",
  "design-systems",
  "ui-ux",
  "accessibility",
  "project-management",
  "soft-skills",
  "blockchain",
  "iot",
  "game-dev"
];

export const proficiencyLevels = [
  { value: 1, name: '1 - Beginner' },
  { value: 2, name: '2 - Novice' },
  { value: 3, name: '3 - Intermediate' },
  { value: 4, name: '4 - Advanced' },
  { value: 5, name: '5 - Expert' },
];
